### ISSUE TITLE
pypi has the madprime version hosted. 

### ISSUE THREAD

**Issue by changeling** [nickreynke/python-gedcom#1]
`pip install python-gedcom` installs the 2012 code.

**Comment by nickreynke** [comment]
Thanks @changeling :) Yeah I was not ready to publish the current state but I am currently preparing a release so there'll be a `v0.2.0dev` soon :)

**Comment by nickreynke** [comment]
New source code is now in the main branch but I am having problems with uploading the new package to PyPI. It may take a bit since I've never done that ^^

**Comment by changeling** [comment]
No worries. Thanks for responding quickly. (Though I've didn't notice until just now. :/ )

**Comment by changeling** [comment]
Here's a question. When the code refers to GEDCOM 5.5, is that accurate, or are we talking about 5.5.1?

**Comment by andersbel** [comment]
I have also noted that an old version is on PyPI.
After downloading a zip-file with master, I installed from that one using
pip3 install --user --no-index /path/to/python-gedcom-master.zip

**Comment by nickreynke** [comment]
Hey @changeling and @andersbel! SORRY for the **late** reply. There is now a new version (`v0.2.2dev`) available! ✌
