### ISSUE TITLE
given/surname_match methods should be case insensitive

### ISSUE THREAD

**Issue by nomadyow** [nickreynke/python-gedcom#10]
given_match and surname_match are currently case sensitive substring searches for their respective fields.

I propose that these should be case insensitive searches.  It does not seem reasonable that the user would intend to use the case insensitivity to distinguish be between (for example)

John Smith
and 
John SMITH

I propose the case insensitivity because there are essentially to schools of thought on storing names.  The "traditional" school of thought says to store all names in uppercase for ease of readability vs. the typical first letter capitalization.  This improves the hit rate of the *content* of the fields rather than its *formatting*.

Backwards compatibility is not broken, however this would potentially change the expected results.

I will submit the patch to this as well as other changes in a PR

**Comment by nickreynke** [comment]
@nomadyow merged and commented in #11 :) Thank you!
