### ISSUE TITLE
trying to separate gedcom into maternal and paternal, error

### ISSUE THREAD

**Issue by sstephans** [nickreynke/python-gedcom#20]
Hello, I'm trying to separate out the maternal vs paternal lines in my gedcom. Here's the code as I have it now:

```
gedcom = Gedcom(file_path)
all_records = gedcom.get_root_child_elements()
home_person = gedcom.get_root_element()
parents = gedcom.get_parents(home_person)
```

and I get the following output:

```
Traceback (most recent call last):
  File "C:\Users\saman\Documents\ancestry\python-gedom-playground\bridgets.py", line 15, in <module>
    parents = gedcom.get_parents(home_person)
  File "C:\Python37\lib\site-packages\gedcom\__init__.py", line 456, in get_parents
    raise ValueError("Operation only valid for elements with %s tag." % GEDCOM_TAG_INDIVIDUAL)
ValueError: Operation only valid for elements with INDI tag.
```

What am I doing wrong?

**Comment by nomadyow** [comment]
The root element is not a person - its a special element that "anchors" the dictionary.  This is done because all the elements become a "child" to the "parent" element.

In your case you want to iterate through your "all_records" and look for individuals:
all_records = gedcom.get_root_child_elements()
for record in all_records:
    if record.is_individual():
        parents = gedcom.get_parents(record)
            for parent in parents:
                print (parent.get_name())

**Comment by sstephans** [comment]
Thank you.

**Comment by nickreynke** [comment]
This behavior will become more clear with version 1.0.0 @sstephans :) There will be derived `Element` classes like `RootElement` and `IndividualElement`.

Thank you! :)

**Comment by sstephans** [comment]
That's exciting! I've been having a lot of fun with this repo, using it to make custom google maps of ancestors. Thanks for your work!
